name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - 'main'
      - 'development'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - 

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      - name: Install Dependencies
        run: npm install
      
      - name: Run Jest Tests
        run: npm test  

      - name: Check Code Coverage
        run: npm run coverage  
      
      - name: Linting with ESLint
        run: npm run lint

      - name: Build
        run: npm run build  

      - name: Deploy to Production
            if: github.ref == 'refs/heads/main'
            run: |
                render deploy --config render.yaml

# https://tenzi-backend-ajwc.onrender.com/


