name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/*'  # Adjust this according to your branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use your desired Node.js version

      - name: Install Dependencies
        run: npm install
      
      - name: Run Jest Tests
        run: npm test  # Adjust this command according to your test setup

      - name: Check Code Coverage
        run: npm run coverage  
      
      - name: Linting with ESLint
        run: npm run lint

      - name: Build
        run: npm run build  # Adjust this command for your build process

      - name: Deploy
        # Add deployment steps (e.g., deploying to a server, cloud platform, etc.)
        # This depends on how you deploy your Express.js app
